"""Roaming catalog - country lookup over the bundled telekom.sk snapshot.

The snapshot at ``data/roaming_sk.json`` is generated by
:mod:`.roaming_refresh` from https://www.telekom.sk/volania/roaming and holds,
per country: the roaming zone, per-unit prices and available packages for the
three customer segments (paušál / dobíjacia karta / Bez záväzkov), plus partner
network coverage. This module only loads and searches that snapshot - it never
touches the network, so the ``roaming_*`` tools stay fast and deterministic.
"""

from __future__ import annotations

import difflib
import json
import unicodedata
from pathlib import Path
from typing import Any

DATA_PATH = Path(__file__).parent / "data" / "roaming_sk.json"

#: Customer segments as exposed to the LLM (and stored in the snapshot).
SEGMENTS = ("pausal", "dobijacia_karta", "bez_zavazkov")

_MAX_ALTERNATIVES = 8
_FUZZY_CUTOFF = 0.75


def normalize_name(text: str) -> str:
    """Lowercase, trim and strip diacritics so 'Turecko' == 'turecko' == 'TURECKO'."""
    decomposed = unicodedata.normalize("NFKD", text or "")
    stripped = "".join(char for char in decomposed if not unicodedata.combining(char))
    return stripped.lower().strip()


class RoamingCatalog:
    """In-memory search index (name/alias/ISO code -> country) over the snapshot."""

    def __init__(self, snapshot: dict[str, Any]) -> None:
        self.source: str = str(snapshot.get("zdroj") or "")
        self.snapshot_date: str = str(snapshot.get("stiahnute") or "")
        self.countries: list[dict[str, Any]] = [
            country for country in snapshot.get("krajiny") or [] if isinstance(country, dict)
        ]
        self._keys_by_slug: dict[str, frozenset[str]] = {}
        self._by_key: dict[str, list[dict[str, Any]]] = {}
        for country in self.countries:
            keys = {
                str(country.get("nazov") or ""),
                str(country.get("iso2") or ""),
                str(country.get("iso3") or ""),
                *(country.get("aliasy") or []),
            }
            normalized = frozenset(normalize_name(key) for key in keys) - {""}
            self._keys_by_slug[str(country.get("slug") or "")] = normalized
            for key in normalized:
                bucket = self._by_key.setdefault(key, [])
                if not any(existing is country for existing in bucket):
                    bucket.append(country)

    @classmethod
    def load(cls, path: Path | None = None) -> RoamingCatalog:
        """Load the catalog from ``path`` (default: the bundled snapshot)."""
        snapshot = json.loads((path or DATA_PATH).read_text(encoding="utf-8"))
        return cls(snapshot)

    def find(self, query: str) -> tuple[dict[str, Any] | None, list[dict[str, Any]]]:
        """Resolve a country query to ``(match, alternatives)``.

        Exactly one of the results is meaningful: a unique hit returns
        ``(country, [])``; an ambiguous query returns ``(None, candidates)``;
        an unknown query returns ``(None, fuzzy_suggestions)`` (possibly empty).
        Matching is case- and diacritics-insensitive and covers Slovak names,
        CMS aliases (incl. English names and common misspellings) and ISO codes.
        """
        query_key = normalize_name(query)
        if not query_key:
            return None, []

        exact = self._by_key.get(query_key) or []
        if len(exact) == 1:
            return exact[0], []
        if exact:
            return None, exact[:_MAX_ALTERNATIVES]

        substring = [
            country
            for country in self.countries
            if any(query_key in key for key in self._keys_by_slug[str(country.get("slug") or "")])
        ]
        if len(substring) == 1:
            return substring[0], []
        if substring:
            return None, substring[:_MAX_ALTERNATIVES]

        close_keys = difflib.get_close_matches(
            query_key, list(self._by_key), n=_MAX_ALTERNATIVES, cutoff=_FUZZY_CUTOFF
        )
        suggestions: list[dict[str, Any]] = []
        for key in close_keys:
            for country in self._by_key[key]:
                if not any(existing is country for existing in suggestions):
                    suggestions.append(country)
        return None, suggestions[:_MAX_ALTERNATIVES]


def country_payload(country: dict[str, Any], segment: str | None = None) -> dict[str, Any]:
    """Return the tool-facing view of a country, optionally cut to one segment."""
    payload = dict(country)
    payload.pop("slug", None)
    if segment:
        payload["segmenty"] = {segment: (country.get("segmenty") or {}).get(segment)}
    return payload
