"""Intent catalog for Slovak Telekom voice assistant.

Each intent entry:
  route        : one of selfcare | standard_contact_center | tech_selfcare | tech_contact_center
  label        : short Slovak label
  description  : what belongs here
  keywords     : typical words/phrases that signal this intent
  excludes     : common confusables — what does NOT belong here
  disambiguate : list of disambiguation area IDs to check when this intent is suspected
"""

from __future__ import annotations

from typing import Any

INTENT_CATALOG: dict[str, dict[str, Any]] = {
    # ─────────────────────────────────────────────
    # SELFCARE
    # ─────────────────────────────────────────────
    "INVOICE_NOTIFICATION": {
        "route": "selfcare",
        "label": "Notifikačné číslo na faktúru",
        "description": "Zmena alebo nastavenie čísla, na ktoré chodí SMS o vystavenej faktúre.",
        "keywords": ["notifikácia", "sms o faktúre", "notifikačné číslo", "číslo na sms"],
        "excludes": ["zmena doručovania faktúry", "zmena emailu na faktúru", "zmena adresy"],
        "disambiguate": [],
    },
    "INVOICE_CHECK": {
        "route": "selfcare",
        "label": "Overenie úhrady faktúry",
        "description": "Zákazník sa pýta, či jeho faktúra bola zaplatená/uhradená.",
        "keywords": ["zaplatená faktúra", "uhradená faktúra", "či som zaplatil", "overenie platby"],
        "excludes": ["výška dlhu", "výška faktúry", "koľko dlhujem"],
        "disambiguate": [],
    },
    "PAYMENT_DEFERRAL": {
        "route": "selfcare",
        "label": "Odklad platby",
        "description": "Žiadosť o odloženie termínu splatnosti faktúry.",
        "keywords": ["odklad", "odložiť platbu", "neskorší termín platby", "predĺžiť splatnosť"],
        "excludes": [],
        "disambiguate": [],
    },
    "PAYMENT_CALENDAR": {
        "route": "selfcare",
        "label": "Splátkový kalendár",
        "description": "Nastavenie splátkového kalendára na úhradu dlhu.",
        "keywords": ["splátkový kalendár", "splátky", "rozložiť dlh", "splácať"],
        "excludes": [],
        "disambiguate": [],
    },
    "DEBT_AMOUNT": {
        "route": "selfcare",
        "label": "Výška dlhu / faktúry",
        "description": "Otázka na výšku aktuálneho dlhu alebo faktúry.",
        "keywords": [
            "koľko dlhujem",
            "výška faktúry",
            "koľko mám zaplatiť",
            "suma faktúry",
            "dlžná čiastka",
        ],
        "excludes": ["či je faktúra zaplatená"],
        "disambiguate": [],
    },
    "PAYMENT_OPTIONS": {
        "route": "selfcare",
        "label": "Spôsoby úhrady",
        "description": "Otázky, akými spôsobmi je možné uhradiť faktúru.",
        "keywords": [
            "ako zaplatiť",
            "spôsoby platby",
            "platba kartou",
            "platba prevodom",
            "kde zaplatiť",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "INVOICE_INFORMATION": {
        "route": "selfcare",
        "label": "Informácie o faktúre",
        "description": "Zákazník chce informácie o svojej faktúre alebo podrobnosti k jednotlivým položkám.",
        "keywords": [
            "faktúra",
            "vyúčtovanie",
            "čo je na faktúre",
            "položky faktúry",
            "prečo taká suma",
        ],
        "excludes": ["zmena fakturačnej adresy", "zmena doručovania"],
        "disambiguate": [],
    },
    "OVERPAYMENT": {
        "route": "selfcare",
        "label": "Preplatok",
        "description": "Vrátenie preplatku zákazníkovi.",
        "keywords": ["preplatok", "vrátenie peňazí", "preplatil som", "vrátiť preplatok"],
        "excludes": [],
        "disambiguate": [],
    },
    "DIRECT_DEBIT": {
        "route": "selfcare",
        "label": "Inkaso / SEPA direct debit",
        "description": "Témy výlučne týkajúce sa SEPA inkasa a opakovaného sťahovania z účtu.",
        "keywords": ["inkaso", "direct debit", "sepa", "stiahnutie z účtu", "bankový príkaz"],
        "excludes": ["mobilná platba", "platba mobilom", "google pay", "apple pay"],
        "disambiguate": [],
    },
    "PAYMENT_REMINDER": {
        "route": "selfcare",
        "label": "Upomienka",
        "description": "Otázky k upomienke na platbu.",
        "keywords": ["upomienka", "dostal som upomienku", "upomienka na platbu"],
        "excludes": [],
        "disambiguate": [],
    },
    "BILLING_PERIOD": {
        "route": "selfcare",
        "label": "Fakturačné obdobie",
        "description": "Otázky na fakturačné obdobie alebo dátum vystavenia faktúry.",
        "keywords": [
            "fakturačné obdobie",
            "kedy mi príde faktúra",
            "dátum faktúry",
            "kedy sa fakturuje",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "SERVICE_RECONNECT": {
        "route": "selfcare",
        "label": "Opätovné zapojenie služby",
        "description": "Znovuzapojenie odpojených služieb po uhradení faktúry.",
        "keywords": ["znovu zapojiť", "obnoviť službu", "opätovné zapojenie", "zaplatil som obnov"],
        "excludes": [],
        "disambiguate": [],
    },
    "TKZ": {
        "route": "selfcare",
        "label": "Telekomunikačné zariadenie / výkopové práce",
        "description": "Vyjadrenie telekomunikačnej siete, povolenia, výkopové práce.",
        "keywords": [
            "tkz",
            "vyjadrenie siete",
            "výkopové práce",
            "povolenie telekom",
            "trasovanie káblov",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "CALL_LOG": {
        "route": "selfcare",
        "label": "Výpis hovorov",
        "description": "Požiadavka na výpis hovorov alebo SMS.",
        "keywords": ["výpis hovorov", "zoznam hovorov", "volal som", "história hovorov"],
        "excludes": [],
        "disambiguate": [],
    },
    "SMART_CARD": {
        "route": "selfcare",
        "label": "Aktivácia smart karty",
        "description": "Aktivácia smart karty do settopboxu.",
        "keywords": ["smart karta", "aktivácia karty do boxu", "karta do settopboxu"],
        "excludes": [],
        "disambiguate": [],
    },
    "TELEKOM_CENTER_INFO": {
        "route": "selfcare",
        "label": "Info o Telekom centre",
        "description": "Kontakty, otváracie hodiny alebo poloha Telekom centra / predajne.",
        "keywords": [
            "telekom centrum",
            "predajňa",
            "otváracie hodiny",
            "pobočka",
            "kde je predajňa",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "ROAMING_INFO": {
        "route": "selfcare",
        "label": "Roaming",
        "description": "Zapnutie, ceny a limity roamingu.",
        "keywords": [
            "roaming",
            "zahraničie",
            "volanie v zahraničí",
            "dáta v zahraničí",
            "roamingový balík",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "PIN_PUK": {
        "route": "selfcare",
        "label": "PIN / PUK kód",
        "description": "Žiadosť o PIN alebo PUK kód, odblokovanie SIM karty alebo telefónu.",
        "keywords": [
            "pin kód",
            "puk kód",
            "zabudol som pin",
            "zablokovaná sim",
            "odblokovanie sim",
        ],
        "excludes": ["pid kód", "id kód zákazníka"],
        "disambiguate": [],
    },
    "PID_ID_CODE_INFO": {
        "route": "selfcare",
        "label": "PID / ID kód zákazníka",
        "description": "Informácie o PID alebo ID kóde zákazníka — bezpečnostnom faktore na overenie totožnosti.",
        "keywords": [
            "pid kód",
            "id kód",
            "overovací kód zákazníka",
            "bezpečnostný kód",
            "čo je pid",
        ],
        "excludes": ["pin kód", "puk kód"],
        "disambiguate": [],
    },
    "TV_CHANNELS": {
        "route": "selfcare",
        "label": "Zoradenie kanálov",
        "description": "Usporiadanie alebo zoradenie kanálov na televízore.",
        "keywords": [
            "zoradenie kanálov",
            "poradie kanálov",
            "usporiadanie programov",
            "preusporiadať kanály",
        ],
        "excludes": ["tv balíčky", "magio tv", "technický problém s tv"],
        "disambiguate": [],
    },
    "VOYO": {
        "route": "selfcare",
        "label": "VOYO",
        "description": "Otázky k službe VOYO — aktivácia, deaktivácia, prístup, technické problémy, poplatky.",
        "keywords": ["voyo", "voyo predplatné", "aktivovať voyo", "zrušiť voyo", "problém s voyo"],
        "excludes": ["magio tv", "iptv"],
        "disambiguate": ["voyo_vs_tv"],
    },
    "USAGE_OVERVIEW": {
        "route": "selfcare",
        "label": "Prehľad spotreby",
        "description": "Prehľad spotreby dát, minút alebo SMS.",
        "keywords": [
            "spotreba dát",
            "koľko som vyčerpal",
            "prehľad spotreby",
            "zostatok dát",
            "koľko minút mám",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "PARENTAL_LOCK": {
        "route": "selfcare",
        "label": "Rodičovský zámok",
        "description": "Nastavenie rodičovského zámku na zariadení alebo službe.",
        "keywords": [
            "rodičovský zámok",
            "detský zámok",
            "zablokovať kanály pre deti",
            "vekové obmedzenie",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "CHRISTMAS_OFFER": {
        "route": "selfcare",
        "label": "Vianočná ponuka",
        "description": "Aktuálna vianočná ponuka Telekomu.",
        "keywords": ["vianočná ponuka", "vianočná akcia", "vianoce telekom"],
        "excludes": [],
        "disambiguate": [],
    },
    "TOPUP_CREDIT": {
        "route": "selfcare",
        "label": "Dobitie kreditu",
        "description": "Dobitie kreditu na predplatenej karte.",
        "keywords": ["dobitie kreditu", "dobiť kredit", "nabíjanie kreditu", "kredit na sim"],
        "excludes": ["problém s dobitím"],
        "disambiguate": [],
    },
    "INVOICE_COPY": {
        "route": "selfcare",
        "label": "Kópia faktúry",
        "description": "Žiadosť o kópiu alebo odpis faktúry.",
        "keywords": ["kópia faktúry", "odpis faktúry", "duplikát faktúry", "zaslať faktúru znovu"],
        "excludes": [],
        "disambiguate": [],
    },
    "LOSS_THEFT": {
        "route": "selfcare",
        "label": "Strata / krádež",
        "description": "Hlásenie straty alebo krádeže zariadenia, žiadosť o zablokovanie čísla.",
        "keywords": ["stratil som telefón", "ukradli mi telefón", "zablokovat číslo", "strata sim"],
        "excludes": [],
        "disambiguate": [],
    },
    "VOICE_BIOMETRY": {
        "route": "selfcare",
        "label": "Hlasová biometria",
        "description": "Aktivácia, informácie alebo správa hlasovej biometrie.",
        "keywords": ["hlasová biometria", "biometria", "aktivovať hlasovú biometriu"],
        "excludes": [],
        "disambiguate": [],
    },
    "MAGENTA_MOMENTS": {
        "route": "selfcare",
        "label": "Magenta Moments",
        "description": "Otázky k vernostnému programu Magenta Moments.",
        "keywords": ["magenta moments", "body magenta", "vernostný program", "odmeny telekom"],
        "excludes": ["magenta one"],
        "disambiguate": [],
    },
    "INVOICE_RESEND": {
        "route": "selfcare",
        "label": "Preposlanie faktúry",
        "description": "Požiadavka na preposlanie faktúry, ktorá nebola doručená.",
        "keywords": [
            "neprishla faktúra",
            "nezískal som faktúru",
            "preposlať faktúru",
            "nedoručená faktúra",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "EKO_COUPON": {
        "route": "selfcare",
        "label": "Eko kupón / recyklácia",
        "description": "Otázky ohľadom eko kupónu a odovzdania starého zariadenia na recykláciu.",
        "keywords": [
            "eko kupón",
            "recyklácia zariadenia",
            "odovzdanie starého telefónu",
            "ekologická likvidácia",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "SWIPE": {
        "route": "selfcare",
        "label": "Swipe",
        "description": "Otázky ohľadom služby Swipe, paušálu pre mladých, aplikácie Swipe.",
        "keywords": ["swipe", "swipe paušál", "swipe app", "paušál pre mladých"],
        "excludes": [],
        "disambiguate": [],
    },
    # ─────────────────────────────────────────────
    # STANDARD_CONTACT_CENTER
    # ─────────────────────────────────────────────
    "AKTIVACIA": {
        "route": "standard_contact_center",
        "label": "Aktivácia novej služby",
        "description": "Žiadosť o aktiváciu novej služby — internet, TV balík, easy, doplnkové balíčky.",
        "keywords": ["aktivovať", "aktivácia", "zapnúť internet", "zapnúť tv", "nová služba"],
        "excludes": ["predĺženie viazanosti", "zmena programu"],
        "disambiguate": ["service_change_vs_fault"],
    },
    "PROLONGACIA": {
        "route": "standard_contact_center",
        "label": "Predĺženie viazanosti",
        "description": "Žiadosť o predĺženie viazanosti alebo obnovenie zmluvy.",
        "keywords": ["predĺžiť viazanosť", "obnoviť zmluvu", "koniec viazanosti", "prolongácia"],
        "excludes": [],
        "disambiguate": [],
    },
    "VIAZANOST": {
        "route": "standard_contact_center",
        "label": "Viazanosť",
        "description": "Otázka na dĺžku viazanosti alebo dátum skončenia zmluvy.",
        "keywords": [
            "viazanosť",
            "dokedy mám viazanosť",
            "dátum viazanosti",
            "kedy mi končí zmluva",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "ADDON_SERVICES": {
        "route": "standard_contact_center",
        "label": "Doplnkové služby / balíčky",
        "description": "Aktivácia doplnkových balíčkov, roamingových balíčkov, navýšenie dát alebo iných doplnkov.",
        "keywords": [
            "doplnkový balíček",
            "pridať balíček",
            "roamingový balíček",
            "navýšiť dáta",
            "extra balíček",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "CLICK_SECURITY": {
        "route": "standard_contact_center",
        "label": "Click Security",
        "description": "Informácie a aktivácia služby Click Security.",
        "keywords": ["click security", "bezpečnostná služba", "ochrana internetu"],
        "excludes": [],
        "disambiguate": [],
    },
    "SERVICE_TERMINATION": {
        "route": "standard_contact_center",
        "label": "Ukončenie zmluvy / zrušenie služby",
        "description": "Žiadosť o ukončenie zmluvy alebo zrušenie konkrétnej služby.",
        "keywords": [
            "zrušiť zmluvu",
            "ukončiť zmluvu",
            "zrušiť službu",
            "odísť od telekomu",
            "vypovedanie zmluvy",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "INTERNET_TECH_CHANGE": {
        "route": "standard_contact_center",
        "label": "Zmena technológie internetu",
        "description": "Žiadosť o zmenu technológie internetu (napr. z DSL na optiku).",
        "keywords": [
            "zmena technológie",
            "prejsť na optiku",
            "z dsl na optiku",
            "fiber",
            "optický internet",
        ],
        "excludes": ["technický problém s internetom"],
        "disambiguate": ["service_change_vs_fault"],
    },
    "SERVICE_ADMINISTRATION": {
        "route": "standard_contact_center",
        "label": "Zmena hlavnej služby",
        "description": "Zmena paušálu, zmena programu, zmena hlavného balíka.",
        "keywords": [
            "zmeniť paušál",
            "zmena programu",
            "iný paušál",
            "upgradovať paušál",
            "zmena balíka",
        ],
        "excludes": ["technický problém"],
        "disambiguate": ["service_change_vs_fault"],
    },
    "CONTRACT_INFO": {
        "route": "standard_contact_center",
        "label": "Informácie o zmluve",
        "description": "Otázky týkajúce sa zmluvy — podmienky, obsah, platnosť.",
        "keywords": ["zmluva", "podmienky zmluvy", "obsah zmluvy", "čo je v zmluve"],
        "excludes": [],
        "disambiguate": [],
    },
    "MOBILE_PAYMENT_SETUP": {
        "route": "standard_contact_center",
        "label": "Mobilné platby",
        "description": "Jednorazové alebo opakované platby cez mobilnú peňaženku alebo operátora.",
        "keywords": [
            "mobilná platba",
            "platba cez mobil",
            "google pay",
            "apple pay",
            "platba operátorom",
        ],
        "excludes": ["inkaso", "sepa"],
        "disambiguate": [],
    },
    "PORTATION": {
        "route": "standard_contact_center",
        "label": "Portácia",
        "description": "Prenesenie čísla od iného operátora k Telekomu alebo od Telekomu.",
        "keywords": ["portácia", "preniesť číslo", "prenos čísla", "prestupiť k telekomu"],
        "excludes": ["prepísanie čísla na inú osobu"],
        "disambiguate": [],
    },
    "SERVICE_TRANSFER": {
        "route": "standard_contact_center",
        "label": "Zmena adresy / prepísanie čísla",
        "description": "Zmena adresy poskytovanej služby alebo prepísanie čísla/služby na inú osobu.",
        "keywords": [
            "zmena adresy služby",
            "prepísanie čísla",
            "prevod čísla na inú osobu",
            "zmena majiteľa čísla",
        ],
        "excludes": ["portácia — prenos k inému operátorovi"],
        "disambiguate": [],
    },
    "ESIM": {
        "route": "standard_contact_center",
        "label": "eSIM",
        "description": "Žiadosť o aktiváciu eSIM.",
        "keywords": ["esim", "e-sim", "virtuálna sim", "aktivovať esim"],
        "excludes": [],
        "disambiguate": [],
    },
    "PRODUCTS_INFO": {
        "route": "standard_contact_center",
        "label": "Informácie o produktoch",
        "description": "Všeobecné otázky o produktoch — internet, TV, telefónovanie, dáta, paušály.",
        "keywords": [
            "informácie o internete",
            "čo ponúkate",
            "cenník",
            "aké paušály máte",
            "tv balíčky info",
        ],
        "excludes": ["záujem o kúpu", "technický problém"],
        "disambiguate": [],
    },
    "PRODUCTS_INTEREST": {
        "route": "standard_contact_center",
        "label": "Záujem o produkt",
        "description": "Zákazník má záujem o niektorý produkt Telekomu.",
        "keywords": [
            "chcem si zobrať internet",
            "zaujíma ma paušál",
            "chcem televíziu",
            "mám záujem",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "PREPAID_INFO": {
        "route": "standard_contact_center",
        "label": "Predplatená karta",
        "description": "Informácie o prepaid službách a predplatených kartách.",
        "keywords": ["predplatená karta", "prepaid", "predplatenka", "kredit"],
        "excludes": ["dobitie kreditu"],
        "disambiguate": [],
    },
    "EASY_INFO": {
        "route": "standard_contact_center",
        "label": "Služba EASY — info",
        "description": "Otázky alebo informácie o službe EASY — popis, cena, podmienky, fungovanie.",
        "keywords": ["easy", "easy služba", "čo je easy", "easy cena"],
        "excludes": ["aktivácia easy", "zmena easy", "zrušenie easy"],
        "disambiguate": [],
    },
    "TV_PACKAGES": {
        "route": "standard_contact_center",
        "label": "TV balíčky",
        "description": "Témy týkajúce sa TV balíčkov (maďarský balík, extra balík a pod.).",
        "keywords": [
            "tv balíček",
            "maďarský balík",
            "extra balík",
            "hbo balík",
            "pridať tv kanály",
        ],
        "excludes": ["technický problém s tv", "zoradenie kanálov"],
        "disambiguate": [],
    },
    "RETENTION_QUERY": {
        "route": "standard_contact_center",
        "label": "Retenčné ponuky",
        "description": "Zákazník sa pýta na retenčné ponuky.",
        "keywords": [
            "retenčná ponuka",
            "vernostná ponuka",
            "chcem lepšiu ponuku",
            "zvažujem odísť",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "PROMOTIONAL_OFFER": {
        "route": "standard_contact_center",
        "label": "Akciové ponuky",
        "description": "Iné akciové alebo špeciálne ponuky.",
        "keywords": ["akcia", "akciová ponuka", "špeciálna ponuka", "zľava"],
        "excludes": [],
        "disambiguate": [],
    },
    "NETFLIX": {
        "route": "standard_contact_center",
        "label": "Netflix",
        "description": "Témy týkajúce sa Netflix služby v rámci Telekomu.",
        "keywords": ["netflix", "netflix v paušáli", "netflix v tv"],
        "excludes": [],
        "disambiguate": [],
    },
    "INSURANCE_QUERY": {
        "route": "standard_contact_center",
        "label": "Poistenie zariadenia",
        "description": "Otázky alebo aktivácia poistenia zariadenia.",
        "keywords": ["poistenie telefónu", "poistenie zariadenia", "poistka", "poistenie mobilu"],
        "excludes": [],
        "disambiguate": [],
    },
    "LOGIN_DETAILS": {
        "route": "standard_contact_center",
        "label": "Prihlasovacie údaje",
        "description": "Prihlasovacie údaje, heslo na Magio GO, kód na Magio GO.",
        "keywords": [
            "zabudol som heslo",
            "prihlasovacie údaje",
            "magio go heslo",
            "kód magio",
            "login",
        ],
        "excludes": ["pin kód", "puk kód"],
        "disambiguate": [],
    },
    "INVOICE_CHANGE": {
        "route": "standard_contact_center",
        "label": "Zmena fakturačných údajov",
        "description": "Zmena fakturačnej adresy, emailu na faktúry, formy doručenia faktúr.",
        "keywords": [
            "zmena fakturačnej adresy",
            "zmeniť email na faktúru",
            "elektronická faktúra",
            "zmena doručovania faktúry",
        ],
        "excludes": ["informácie o faktúre", "notifikačné sms číslo"],
        "disambiguate": [],
    },
    "INVOICE": {
        "route": "standard_contact_center",
        "label": "Ostatné fakturačné témy",
        "description": "Zvyšné fakturačné témy, ktoré nespadajú do iných fakturačných intentov.",
        "keywords": [],
        "excludes": [],
        "disambiguate": [],
    },
    "SIM_ACTIVATION_SWAP": {
        "route": "standard_contact_center",
        "label": "Aktivácia / výmena SIM",
        "description": "Aktivácia novej SIM karty alebo výmena existujúcej.",
        "keywords": ["aktivovať sim", "nová sim karta", "výmena sim", "dostala som novú kartu"],
        "excludes": ["puk kód", "esim"],
        "disambiguate": [],
    },
    "DEVICE_BROKEN": {
        "route": "standard_contact_center",
        "label": "Pokazené zariadenie",
        "description": "Zariadenie (telefón, router, settopbox) je pokazené — zákazník hlási HW poruchu zariadenia ako takého.",
        "keywords": [
            "pokazený telefón",
            "nefunguje zariadenie",
            "porucha zariadenia",
            "oprava zariadenia",
        ],
        "excludes": ["nefunguje internet", "nefunguje tv"],
        "disambiguate": [],
    },
    "APP_PORTAL_ISSUE": {
        "route": "standard_contact_center",
        "label": "Problém s aplikáciou / portálom",
        "description": "Problém s aplikáciou Magio GO, Telekom portálom alebo iným digitálnym kanálom.",
        "keywords": [
            "magio go nefunguje",
            "aplikácia nefunguje",
            "portál nefunguje",
            "môj telekom nefunguje",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "TOPUP_PROBLEM": {
        "route": "standard_contact_center",
        "label": "Problém s dobitím kreditu",
        "description": "Zákazník má technický alebo iný problém s dobitím kreditu.",
        "keywords": [
            "nešlo dobitie",
            "dobitie neprebehlo",
            "problém s dobitím",
            "kredit sa nedobiť",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "COURIER_QUERY": {
        "route": "standard_contact_center",
        "label": "Kuriér",
        "description": "Otázky ku kuriérovi alebo zmena doručenia objednávky.",
        "keywords": ["kuriér", "doručenie", "zmena doručenia", "kedy príde kuriér", "balík"],
        "excludes": [],
        "disambiguate": [],
    },
    "I_WAS_CONTACTED_BY_TELEKOM": {
        "route": "standard_contact_center",
        "label": "Bol som kontaktovaný Telekomom",
        "description": "Zákazník reaguje na zmeškaný hovor alebo kontakt od Telekomu.",
        "keywords": [
            "volali ste mi",
            "zmeškali ste mi hovor",
            "telekom mi volal",
            "spätný hovor",
            "reagoval na hovor",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "VULGARNE_SLOVA": {
        "route": "standard_contact_center",
        "label": "Vulgárne slová",
        "description": "Volajúci používa vulgárne výrazy; eskalovať k agentovi so špeciálnym postupom.",
        "keywords": [],
        "excludes": [],
        "disambiguate": [],
    },
    "CLAIMS": {
        "route": "standard_contact_center",
        "label": "Reklamácia",
        "description": "Podanie novej reklamácie alebo kontrola stavu existujúcej reklamácie.",
        "keywords": ["reklamácia", "podať reklamáciu", "chcem reklamovať", "stav reklamácie"],
        "excludes": [],
        "disambiguate": [],
    },
    "NEW_PHONE_ELIGIBILITY": {
        "route": "standard_contact_center",
        "label": "Nárok na nový telefón",
        "description": "Zistenie, či má zákazník nárok na nový telefón (upgrade).",
        "keywords": ["nárok na nový telefón", "kedy môžem dostať nový telefón", "upgrade telefónu"],
        "excludes": [],
        "disambiguate": [],
    },
    "HW_INTEREST": {
        "route": "standard_contact_center",
        "label": "Záujem o nové zariadenie",
        "description": "Zákazník má záujem o nové zariadenie (telefón, tablet) k paušálu.",
        "keywords": [
            "chcem nový telefón",
            "záujem o zariadenie",
            "telefón k paušálu",
            "nové zariadenie",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "ORDER_STATUS": {
        "route": "standard_contact_center",
        "label": "Stav objednávky",
        "description": "Otázky na stav existujúcej objednávky.",
        "keywords": [
            "stav objednávky",
            "kde je moja objednávka",
            "objednal som",
            "kedy príde objednávka",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "ROUTER_REPLACEMENT_CALLBACK": {
        "route": "standard_contact_center",
        "label": "Výmena routera — notifikácia",
        "description": "Zákazník reaguje na SMS, email alebo hovor o bezplatnej výmene routera.",
        "keywords": [
            "dostal som sms o výmene routera",
            "výmena routra",
            "bezplatná výmena routera",
            "notifikácia o routri",
        ],
        "excludes": ["router nefunguje", "technická porucha routra"],
        "disambiguate": ["router_type"],
    },
    "MAGENTA_ONE": {
        "route": "standard_contact_center",
        "label": "Magenta One",
        "description": "Otázky ohľadom skupiny Magenta One a benefitov v rámci skupiny.",
        "keywords": ["magenta one", "rodinná skupina", "skupinový paušál", "benefity magenta one"],
        "excludes": ["magenta moments"],
        "disambiguate": [],
    },
    "OPERATOR": {
        "route": "standard_contact_center",
        "label": "Prepojenie na operátora",
        "description": "Zákazník žiada prepojenie na živého operátora.",
        "keywords": [
            "operátor",
            "spojiť s operátorom",
            "živý agent",
            "chcem hovoriť s človekom",
            "ľudský agent",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "GIBBERISH": {
        "route": "standard_contact_center",
        "label": "Nezrozumiteľný vstup",
        "description": "Text je nezrozumiteľný — prevažne náhodné znaky alebo chybné ASR.",
        "keywords": [],
        "excludes": [],
        "disambiguate": [],
    },
    "NONSPEC_ISSUE": {
        "route": "standard_contact_center",
        "label": "Nešpecifikovaný problém",
        "description": (
            "Nešpecifikovaný problém. Zákazník hovorí 'nejde mi' / 'nefunguje' bez upresnenia. "
            "NEPOUŽIŤ ak je zmienená konkrétna služba (→ TECH_SELFCARE) alebo 'porucha' ako samostatné slovo (→ OUTAGE)."
        ),
        "keywords": ["nefunguje mi", "mám problém", "nejde mi niečo", "potrebujem pomoc"],
        "excludes": [
            "nejde mi internet (→ INTERNET_NO_SERVICE)",
            "nefunguje tv (→ TV_FAILURE)",
            "technická podpora (→ OUTAGE)",
            "porucha (→ OUTAGE)",
        ],
        "disambiguate": ["tech_vs_nontech"],
    },
    # ─────────────────────────────────────────────
    # TECH_SELFCARE
    # ─────────────────────────────────────────────
    "TV_FAILURE": {
        "route": "tech_selfcare",
        "label": "Porucha televízie",
        "description": (
            "Televízia, Magio SAT, IPTV nefunguje alebo vypadáva. Problém so settopboxom. "
            "Patrí sem aj 'nejde mi televízia', 'výpadok signálu'. "
            "NEPATRÍ sem všeobecné otázky o TV."
        ),
        "keywords": [
            "nefunguje tv",
            "nejde mi televízia",
            "výpadok tv",
            "settopbox nefunguje",
            "magio sat porucha",
            "tv vypadáva",
        ],
        "excludes": ["tv balíčky", "zoradenie kanálov", "voyo"],
        "disambiguate": ["voyo_vs_tv"],
    },
    "PSTN_FAILURE": {
        "route": "tech_selfcare",
        "label": "Porucha pevnej linky",
        "description": "Pevná linka nefunguje (aparát, prístroj). NEPATRÍ sem všeobecné témy o pevnej linke.",
        "keywords": [
            "nefunguje pevná linka",
            "porucha linky",
            "aparát nefunguje",
            "prístroj nefunguje",
            "pevná linka je mŕtva",
        ],
        "excludes": ["všeobecné informácie o pevnej linke"],
        "disambiguate": [],
    },
    "INTERNET_NO_SERVICE": {
        "route": "tech_selfcare",
        "label": "Internet úplne nefunguje",
        "description": (
            "Internet (metalický, optický, GPON) je úplne nedostupný. "
            "Patrí sem 'nejde mi internet', 'porucha internetu', 'nefunguje internet'. "
            "NEPATRÍ sem všeobecné otázky o internete."
        ),
        "keywords": [
            "nefunguje internet",
            "nejde mi internet",
            "internet nefunguje",
            "výpadok internetu",
            "porucha internetu",
        ],
        "excludes": ["pomalý internet", "internet vypadáva občas"],
        "disambiguate": ["internet_fault_type", "wifi_vs_internet"],
    },
    "INTERNET_SLOW": {
        "route": "tech_selfcare",
        "label": "Pomalý internet / výpadky",
        "description": "Internet je pomalý alebo občas vypadáva. NEPATRÍ sem úplný výpadok internetu.",
        "keywords": [
            "pomalý internet",
            "internet vypadáva",
            "nestabilný internet",
            "slabý internet",
            "internet ide pomaly",
        ],
        "excludes": ["internet úplne nefunguje"],
        "disambiguate": ["internet_fault_type"],
    },
    "HW_WIFI_ROUTER": {
        "route": "tech_selfcare",
        "label": "Problém s routerom (HW)",
        "description": (
            "HW problém s routerom alebo wifi routerom — nefunguje, treba zapojiť, nový router. "
            "PREFEROVAŤ keď je v utterance zmienený router. "
            "NEPATRÍ sem výmena routera na základe SMS notifikácie (→ ROUTER_REPLACEMENT_CALLBACK)."
        ),
        "keywords": [
            "nefunguje router",
            "router nefunguje",
            "wifi router problém",
            "zapojenie routra",
            "bliká router",
        ],
        "excludes": ["dostal som sms o výmene routera"],
        "disambiguate": ["router_type", "wifi_vs_internet"],
    },
    "MOBILE_ISSUES": {
        "route": "tech_selfcare",
        "label": "Problémy s mobilnou linkou / volaniami",
        "description": "Problémy s mobilnou linkou, GSM, telefonovaním alebo SIM kartou.",
        "keywords": [
            "mobilná linka nefunguje",
            "neviem volať",
            "nefunguje volanie",
            "gsm problém",
            "sim karta problém",
        ],
        "excludes": ["mobilné dáta", "mobilný internet"],
        "disambiguate": ["mobile_issue_type"],
    },
    "MOBILE_INTERNET": {
        "route": "tech_selfcare",
        "label": "Problémy s mobilnými dátami",
        "description": "Problémy s mobilnými dátami alebo mobilným internetom. NEPATRÍ sem všeobecné témy o mobilných dátach.",
        "keywords": [
            "mobilné dáta nefungujú",
            "mobilný internet nefunguje",
            "nefungujú dáta",
            "nejde mi internet v mobile",
        ],
        "excludes": ["mobilné volania", "volania"],
        "disambiguate": ["mobile_issue_type"],
    },
    "TECHNICIAN_REQUEST": {
        "route": "tech_selfcare",
        "label": "Objednávka technika",
        "description": "Zákazník chce objednať technika alebo servisný zásah.",
        "keywords": [
            "technik",
            "objednať technika",
            "servis",
            "chcem technika domov",
            "návšteva technika",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "SW_WIFI": {
        "route": "tech_selfcare",
        "label": "Softvérový problém s WiFi",
        "description": "Softvérové problémy s WiFi signálom, nastavenie WiFi. NEPATRÍ sem WiFi router ako HW.",
        "keywords": [
            "wifi signál slabý",
            "nastaviť wifi",
            "wifi heslo",
            "wifi nefunguje v izbe",
            "dosah wifi",
        ],
        "excludes": ["router nefunguje", "internet nefunguje úplne"],
        "disambiguate": ["wifi_vs_internet"],
    },
    "OUTAGE": {
        "route": "tech_selfcare",
        "label": "Nahlásenie výpadku / poruchy",
        "description": (
            "Zákazník chce nahlásiť poruchu alebo výpadok bez upresnenia služby, "
            "alebo má výpadok viacerých služieb. "
            "Patrí sem: 'Porucha', 'Mám poruchu', 'technická podpora', 'nahlásenie výpadku'. "
            "MÁ PREDNOSŤ pred NONSPEC_ISSUE."
        ),
        "keywords": [
            "porucha",
            "výpadok",
            "mám výpadok",
            "nahlásenie poruchy",
            "technická podpora",
            "výpadok internetu aj tv",
        ],
        "excludes": ["nejde mi niečo nešpecifikované bez slova porucha"],
        "disambiguate": [],
    },
    # ─────────────────────────────────────────────
    # TECH_CONTACT_CENTER
    # ─────────────────────────────────────────────
    "INFRASTRUCTURE_ISSUES": {
        "route": "tech_contact_center",
        "label": "Problém s infraštruktúrou",
        "description": "Problém s telekomunikačným stĺpom, káblom, padnuté stĺpy, poškodené káble.",
        "keywords": [
            "padnutý stĺp",
            "poškodený kábel",
            "stĺp telekom",
            "kábel na zemi",
            "telekomunikačný stĺp",
        ],
        "excludes": [],
        "disambiguate": [],
    },
    "HW_PHONE_ISSUE": {
        "route": "tech_contact_center",
        "label": "Porucha telefónu (HW)",
        "description": "Fyzická porucha telefónneho aparátu. NEPATRÍ sem iné HW zariadenia.",
        "keywords": [
            "pokazený telefón",
            "telefón nefunguje",
            "porucha telefónu",
            "rozbitý telefón",
        ],
        "excludes": ["router", "settopbox", "modem"],
        "disambiguate": [],
    },
    "TECH_OTHER": {
        "route": "tech_contact_center",
        "label": "Iný technický problém",
        "description": "Komplikovaný technický problém, ktorý nespadá do katalógu TECH_SELFCARE.",
        "keywords": [],
        "excludes": [],
        "disambiguate": [],
    },
}

# Quick lookup: intent_id → route
INTENT_ROUTE: dict[str, str] = {k: v["route"] for k, v in INTENT_CATALOG.items()}

# Intents grouped by route
INTENTS_BY_ROUTE: dict[str, list] = {}
for _intent_id, _data in INTENT_CATALOG.items():
    _route = _data["route"]
    INTENTS_BY_ROUTE.setdefault(_route, []).append(_intent_id)

ROUTE_DESCRIPTIONS: dict[str, str] = {
    "selfcare": "Zákazník vie vyriešiť sám cez digitálny samoobslužný kanál (SMS, aplikácia, web).",
    "standard_contact_center": "Riešenie vyžaduje ľudského agenta kontaktného centra (obchodné zmeny, reklamácie, portácia...).",
    "tech_selfcare": "Skutočná technická porucha — vybaví automatizovaný systém technickej podpory.",
    "tech_contact_center": "Komplikovaný technický problém vyžadujúci špecialistu.",
}

SPECIAL_PRIORITY_RULES = [
    {
        "trigger_description": "Zákazník hovorí 'technická podpora' alebo jeho varianty",
        "trigger_patterns": [
            "technicka podpora",
            "technická podpora",
            "technicku podporu",
            "technickej podpory",
        ],
        "override": {
            "route": "tech_selfcare",
            "intent_id": "OUTAGE",
            "confidence": 0.95,
            "summary": "Zákazník žiada technickú podporu",
            "follow_up_question": "",
        },
    },
]

DISAMBIGUATION_AREAS = [
    "tech_vs_nontech",
    "which_service",
    "router_type",
    "internet_fault_type",
    "mobile_issue_type",
    "wifi_vs_internet",
    "service_change_vs_fault",
    "voyo_vs_tv",
]
