# syntax = docker/dockerfile:1.4

# Per-service Docker image. The selected service name is passed as a build arg.
# The image installs only the dependencies required by that service.

FROM --platform=linux/amd64 python:3.12-slim

ARG service_name
ENV SERVICE_NAME=$service_name \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

# tini for proper signal forwarding, build tools for native deps, uv as the package manager
RUN apt-get update && \
    apt-get install -y --no-install-recommends tini gcc build-essential python3-dev curl && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir uv

RUN useradd --create-home --shell /bin/bash appuser

WORKDIR /app

# Service-specific pinned dependencies (generated by bin/upgrade_packages.py)
COPY requirements/$service_name.txt requirements.txt
RUN uv pip install --system --require-hashes -r requirements.txt

ARG git_commit
ENV GIT_COMMIT=$git_commit

COPY --chown=appuser bin/run_service.py /app/bin/run_service.py
COPY --chown=appuser lib /app/lib
COPY --chown=appuser svc/$service_name /app/svc/$service_name

USER appuser

CMD ["tini", "--", "python", "bin/run_service.py", "--ignore-defaults"]
