apiVersion: v1
kind: Service
metadata:
  name: mcp-telekom-thd-selfcare
  namespace: internal-test
  labels:
    app: mcp-telekom-thd-selfcare
spec:
  type: ClusterIP
  ports:
    - name: mcp
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: healthz
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: mcp-telekom-thd-selfcare
