apiVersion: v1
kind: Service
metadata:
  name: mcp-telekom-thd-selfcare
  labels:
    app: mcp-telekom-thd-selfcare
    team: telekom
  namespace: development
spec:
  selector:
    app: mcp-telekom-thd-selfcare
  ports:
    - name: mcp
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: healthz
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
